_format_version: "1.1"

services:
  - name: auth
    url: http://supabase-auth:9999
    routes:
      - name: auth-all
        strip_path: true
        paths:
          - /auth/v1/
        
  - name: rest
    url: http://supabase-rest:3000
    routes:
      - name: rest-all
        strip_path: true
        paths:
          - /rest/v1/

  - name: realtime
    url: http://supabase-realtime:4000
    routes:
      - name: realtime-all
        strip_path: true
        paths:
          - /realtime/v1/

  - name: storage
    url: http://supabase-storage:5000
    routes:
      - name: storage-all
        strip_path: true
        paths:
          - /storage/v1/

  - name: meta
    url: http://supabase-meta:8080
    routes:
      - name: meta-all
        strip_path: true
        paths:
          - /pg/

  - name: edge-functions
    url: http://supabase-edge-functions:9000
    routes:
      - name: functions-all
        strip_path: true
        paths:
          - /functions/v1/

consumers: []

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - apikey
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
      
  - name: key-auth
    config:
      hide_credentials: false
