name: Deploy to Stage

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: xshuden/uppeng-crm-frontend

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment:
      name: stage
      url: https://stage.uppeng.co

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stage
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGE_HOST }}
          username: root
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker stop crm-stage 2>/dev/null || true
            docker rm crm-stage 2>/dev/null || true
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stage
            docker run -d --name crm-stage --restart unless-stopped -p 3001:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stage
            echo "✅ Stage deployment completed"